import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | NeuroPath AI",
  description:
    "Read the Terms of Service governing the use of NeuroPath AI, an AI-powered personalized learning platform.",
};

export default function TermsOfServicePage() {
  return (
    <main className="max-w-4xl mx-auto px-6 py-12">
      <h1 className="text-3xl font-bold mb-6">Terms of Service</h1>
      <p className="text-sm text-gray-500 mb-8">
        Effective Date: 24 January 2026
      </p>

      <section className="space-y-6">
        <p>
          Welcome to <strong>NeuroPath AI</strong> (“we”, “our”, “us”). By
          accessing or using our platform, you agree to be bound by these Terms
          of Service (“Terms”). If you do not agree, you may not use the service.
        </p>

        <h2 className="text-xl font-semibold">1. Purpose of the Service</h2>
        <p>
          NeuroPath AI is an AI-powered personalized learning platform designed
          to adapt educational content based on learner behavior, preferences,
          and performance. The service is provided for educational and
          informational purposes only.
        </p>

        <h2 className="text-xl font-semibold">2. Eligibility</h2>
        <p>
          You must be at least 13 years old to use NeuroPath AI. By using the
          service, you confirm that you meet this requirement and have the legal
          capacity to agree to these Terms.
        </p>

        <h2 className="text-xl font-semibold">3. User Accounts</h2>
        <ul className="list-disc pl-6">
          <li>You are responsible for maintaining account security.</li>
          <li>You must provide accurate and up-to-date information.</li>
          <li>You are responsible for all activity under your account.</li>
        </ul>

        <h2 className="text-xl font-semibold">4. Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul className="list-disc pl-6">
          <li>Use the platform for unlawful or harmful purposes</li>
          <li>Attempt to exploit, reverse engineer, or disrupt the system</li>
          <li>Upload malicious code or abusive content</li>
          <li>
            Represent AI-generated content as professional, legal, or medical
            advice
          </li>
        </ul>

        <h2 className="text-xl font-semibold">
          5. AI-Generated Content Disclaimer
        </h2>
        <p>
          Content generated by NeuroPath AI is produced using artificial
          intelligence and may contain inaccuracies. We do not guarantee
          educational outcomes, and the platform is not a substitute for formal
          education or professional instruction.
        </p>

        <h2 className="text-xl font-semibold">6. Intellectual Property</h2>
        <p>
          All platform software, branding, algorithms, and content are the
          intellectual property of NeuroPath AI unless otherwise stated. Users
          retain ownership of their original input content.
        </p>

        <h2 className="text-xl font-semibold">7. Termination</h2>
        <p>
          We reserve the right to suspend or terminate access to the platform at
          any time if these Terms are violated.
        </p>

        <h2 className="text-xl font-semibold">8. Limitation of Liability</h2>
        <p>
          NeuroPath AI shall not be liable for any indirect, incidental, or
          consequential damages arising from your use of the service.
        </p>

        <h2 className="text-xl font-semibold">9. Changes to These Terms</h2>
        <p>
          We may update these Terms periodically. Continued use of the platform
          constitutes acceptance of the updated Terms.
        </p>

        <h2 className="text-xl font-semibold">10. Contact</h2>
        <p>
          For questions regarding these Terms, please contact us at:{" "}
          <strong>uneebbhatti3@gmail.com</strong>
        </p>
      </section>
    </main>
  );
}
